# Generated by Django 4.1.3 on 2022-12-25 18:01

from app.models import DateTimeWithoutTZField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_trip",
            field=DateTimeWithoutTZField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="arrival_time",
            field=DateTimeWithoutTZField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=DateTimeWithoutTZField(),
        ),
    ]
