# Generated by Django 4.1.3 on 2022-12-25 19:20

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_order_date_trip_alter_trip_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_trip",
            field=app.models.DateTimeWithoutTZField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="arrival_time",
            field=app.models.DateTimeWithoutTZField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=app.models.DateTimeWithoutTZField(),
        ),
    ]
