# Generated by Django 4.1.3 on 2022-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_client_phone_number_alter_flight_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="capacity",
            field=models.IntegerField(),
        ),
    ]
