# Generated by Django 4.1.3 on 2022-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_car_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(),
        ),
    ]
