# Generated by Django 4.1.3 on 2022-12-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="flight",
        ),
    ]
