# Generated by Django 4.1.3 on 2022-12-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_client_flight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.IntegerField(blank=True, default=123, null=True),
        ),
    ]
