# Generated by Django 4.1.3 on 2022-12-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_client_phone_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Flight",
            new_name="Trip",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="date_flight",
            new_name="date_trip",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="flight",
            new_name="trip",
        ),
    ]
